services:
  # NextJS v13 app running on development mode
  gsites-client-dev:
    container_name: gsites-client-dev
    image: weaponsforge/gsites-client:dev
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    networks:
      - gsites-dev
    volumes:
      - ./client:/opt/client
      - /opt/client/node_modules
      - /opt/client/.next
    ports:
      - "3000:3000"

  # Node CLI for running scripts
  gsites-server-dev:
    container_name: gsites-server-dev
    image: weaponsforge/gsites-server:dev
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    networks:
      - gsites-dev
    volumes:
      - ./server:/opt/server
      - /opt/server/node_modules
    stdin_open: true
    tty: true

networks:
  gsites-dev:
    name: gsites-dev
    external: false
