services:
  # NextJS exported app running on an nginx webserver
  gsites-client-prod:
    container_name: gsites-client-prod
    image: weaponsforge/gsites-client:latest
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    networks:
      - gsites-prod
    ports:
      - "3000:3000"

networks:
  gsites-prod:
    name: gsites-prod
    external: false
