name: Lint Files

# This workflow lints the client and server directories
# And will trigger on push *any* branch except master and dev
on:
  push:
    branches-ignore:
      - master
      - dev

jobs:
  lint-apps:
    name: Lint
    uses: weaponsforge/reusables/.github/workflows/lint-node-multiple.yml@main
    with:
      node_version: v16.14.2
      paths: "['client', 'server']"
