name: Lint Files

# This workflow lints the client and server directories
# And will trigger on push *any* branch except master and dev
on:
  push:
    branches-ignore:
      - master
      - dev

jobs:
  lint-client:
    name: Lint Client
    uses: weaponsforge/reusables/.github/workflows/lint-node.yml@main
    with:
      node_version: v16.14.2
      path: "./client"

  lint-server:
    name: Lint Server
    uses: weaponsforge/reusables/.github/workflows/lint-node.yml@main
    with:
      node_version: v16.14.2
      path: "./server"